### ISSUE TITLE
unsub to all eventsV2 when scene is fully reset

### ISSUE THREAD

**Issue by nanonull** [c0ffeeartc/EntitasGenericAddon#5]
Hey,

Use case: I reset all systems and also need to unsub to all eventsV2 when scene is unloaded.

Is this correct way to clear all subscriptions in context?

`    /// unsub all
    public void ClearSubscriptions(Context<Entity<TScope>> context) {
      if (Action.ContainsKey(context)) {
        Action.Clear();
      }
    }`

![image](https://user-images.githubusercontent.com/8210414/113342428-25b47580-9337-11eb-8bfb-ba31a5cf8724.png)

![image](https://user-images.githubusercontent.com/8210414/113342988-da4e9700-9337-11eb-9a17-8b79af178939.png)

**Comment by nanonull** [comment]
Do I actually need to clear all subscriptions when reset Entitas systems? I think Generic callbacks don't relate to any state from Entitas, right?
![image](https://user-images.githubusercontent.com/8210414/113344313-93fa3780-9339-11eb-904f-c74aa84800b2.png)

**Comment by c0ffeeartc** [comment]
It's not in the addon yet and definitely should be added.
Your function to unsubscribe from one context looks correct. I'd also add top level function that accepts list of contexts and goes through all event classes.

> Do I actually need to clear all subscriptions when reset Entitas systems? I think Generic callbacks don't relate to any state from Entitas, right?

It depends on a lifetime of listener and observable. OnAny listeners may survive if desired. To keep things simple I'd probably unsubscribe all.


Also Action turned out to be slow for subscribe/unsubscribe when count reaches >10000 inside 1 action. I might add another approach in [Examples](https://github.com/c0ffeeartc/EntitasGenericAddon.Examples)

**Comment by c0ffeeartc** [comment]
I have added `Events2.I.UnsubAll()`. It uses `ActionDict.Clear()` which is garbage unfriendly but will have to do for now.

**Comment by nanonull** [comment]
Cool! Pulling...
